
/*
 * 
 */

package edu.sdsc.nbcr.opal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.4
 * Fri Nov 06 13:47:24 PST 2009
 * Generated source version: 2.2.4
 * 
 */


@WebServiceClient(name = "AppService", 
                  wsdlLocation = "file:GOEliteService.wsdl.xml",
                  targetNamespace = "http://nbcr.sdsc.edu/opal") 
public class AppService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://nbcr.sdsc.edu/opal", "AppService");
    public final static QName AppServicePort = new QName("http://nbcr.sdsc.edu/opal", "AppServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:GOEliteService.wsdl.xml");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:GOEliteService.wsdl.xml");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AppService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AppService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AppServicePortType
     */
    @WebEndpoint(name = "AppServicePort")
    public AppServicePortType getAppServicePort() {
        return super.getPort(AppServicePort, AppServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppServicePortType
     */
    @WebEndpoint(name = "AppServicePort")
    public AppServicePortType getAppServicePort(WebServiceFeature... features) {
        return super.getPort(AppServicePort, AppServicePortType.class, features);
    }

}
