
package edu.sdsc.nbcr.opal;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.4
 * Fri Nov 06 13:47:24 PST 2009
 * Generated source version: 2.2.4
 * 
 */

public final class AppServicePortType_AppServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://nbcr.sdsc.edu/opal", "AppService");

    private AppServicePortType_AppServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AppService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AppService ss = new AppService(wsdlURL, SERVICE_NAME);
        AppServicePortType port = ss.getAppServicePort();  
        
        {
        System.out.println("Invoking launchJob...");
        edu.sdsc.nbcr.opal.types.JobInputType _launchJob_launchJobInput = null;
        try {
            edu.sdsc.nbcr.opal.types.JobSubOutputType _launchJob__return = port.launchJob(_launchJob_launchJobInput);
            System.out.println("launchJob.result=" + _launchJob__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking queryStatus...");
        java.lang.String _queryStatus_queryStatusInput = "";
        try {
            edu.sdsc.nbcr.opal.types.StatusOutputType _queryStatus__return = port.queryStatus(_queryStatus_queryStatusInput);
            System.out.println("queryStatus.result=" + _queryStatus__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAppConfig...");
        edu.sdsc.nbcr.opal.types.AppConfigInputType _getAppConfig_getAppConfigInput = null;
        try {
            edu.sdsc.nbcr.opal.types.AppConfigType _getAppConfig__return = port.getAppConfig(_getAppConfig_getAppConfigInput);
            System.out.println("getAppConfig.result=" + _getAppConfig__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAppMetadata...");
        edu.sdsc.nbcr.opal.types.AppMetadataInputType _getAppMetadata_getAppMetadataInput = null;
        try {
            edu.sdsc.nbcr.opal.types.AppMetadataType _getAppMetadata__return = port.getAppMetadata(_getAppMetadata_getAppMetadataInput);
            System.out.println("getAppMetadata.result=" + _getAppMetadata__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getOutputAsBase64ByName...");
        edu.sdsc.nbcr.opal.types.OutputsByNameInputType _getOutputAsBase64ByName_getOutputAsBase64ByNameInput = null;
        try {
            edu.sdsc.nbcr.opal.types.GetOutputAsBase64ByNameOutput _getOutputAsBase64ByName__return = port.getOutputAsBase64ByName(_getOutputAsBase64ByName_getOutputAsBase64ByNameInput);
            System.out.println("getOutputAsBase64ByName.result=" + _getOutputAsBase64ByName__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getOutputs...");
        java.lang.String _getOutputs_getOutputsInput = "";
        try {
            edu.sdsc.nbcr.opal.types.JobOutputType _getOutputs__return = port.getOutputs(_getOutputs_getOutputsInput);
            System.out.println("getOutputs.result=" + _getOutputs__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking destroy...");
        java.lang.String _destroy_destroyInput = "";
        try {
            edu.sdsc.nbcr.opal.types.StatusOutputType _destroy__return = port.destroy(_destroy_destroyInput);
            System.out.println("destroy.result=" + _destroy__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking launchJobBlocking...");
        edu.sdsc.nbcr.opal.types.JobInputType _launchJobBlocking_launchJobBlockingInput = null;
        try {
            edu.sdsc.nbcr.opal.types.BlockingOutputType _launchJobBlocking__return = port.launchJobBlocking(_launchJobBlocking_launchJobBlockingInput);
            System.out.println("launchJobBlocking.result=" + _launchJobBlocking__return);

        } catch (FaultType e) { 
            System.out.println("Expected exception: FaultType has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
