package edu.sdsc.nbcr.opal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.4
 * Fri Nov 06 13:47:24 PST 2009
 * Generated source version: 2.2.4
 * 
 */
 
@WebService(targetNamespace = "http://nbcr.sdsc.edu/opal", name = "AppServicePortType")
@XmlSeeAlso({edu.sdsc.nbcr.opal.types.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AppServicePortType {

    @WebResult(name = "launchJobOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "launchJobOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/launchJob")
    public edu.sdsc.nbcr.opal.types.JobSubOutputType launchJob(
        @WebParam(partName = "launchJobInput", name = "launchJobInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        edu.sdsc.nbcr.opal.types.JobInputType launchJobInput
    ) throws FaultType;

    @WebResult(name = "queryStatusOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "queryStatusOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/queryStatus")
    public edu.sdsc.nbcr.opal.types.StatusOutputType queryStatus(
        @WebParam(partName = "queryStatusInput", name = "queryStatusInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        java.lang.String queryStatusInput
    ) throws FaultType;

    @WebResult(name = "getAppConfigOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "getAppConfigOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/getAppConfig")
    public edu.sdsc.nbcr.opal.types.AppConfigType getAppConfig(
        @WebParam(partName = "getAppConfigInput", name = "getAppConfigInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        edu.sdsc.nbcr.opal.types.AppConfigInputType getAppConfigInput
    ) throws FaultType;

    @WebResult(name = "getAppMetadataOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "getAppMetadataOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/getAppMetadata")
    public edu.sdsc.nbcr.opal.types.AppMetadataType getAppMetadata(
        @WebParam(partName = "getAppMetadataInput", name = "getAppMetadataInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        edu.sdsc.nbcr.opal.types.AppMetadataInputType getAppMetadataInput
    ) throws FaultType;

    @WebResult(name = "getOutputAsBase64ByNameOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "getOutputAsBase64ByNameOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/getOutputAsBase64ByName")
    public edu.sdsc.nbcr.opal.types.GetOutputAsBase64ByNameOutput getOutputAsBase64ByName(
        @WebParam(partName = "getOutputAsBase64ByNameInput", name = "getOutputAsBase64ByNameInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        edu.sdsc.nbcr.opal.types.OutputsByNameInputType getOutputAsBase64ByNameInput
    ) throws FaultType;

    @WebResult(name = "getOutputsOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "getOutputsOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/getOutputs")
    public edu.sdsc.nbcr.opal.types.JobOutputType getOutputs(
        @WebParam(partName = "getOutputsInput", name = "getOutputsInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        java.lang.String getOutputsInput
    ) throws FaultType;

    @WebResult(name = "destroyOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "destroyOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/destroy")
    public edu.sdsc.nbcr.opal.types.StatusOutputType destroy(
        @WebParam(partName = "destroyInput", name = "destroyInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        java.lang.String destroyInput
    ) throws FaultType;

    @WebResult(name = "launchJobBlockingOutput", targetNamespace = "http://nbcr.sdsc.edu/opal/types", partName = "launchJobBlockingOutput")
    @WebMethod(action = "http://nbcr.sdsc.edu/opal/launchJobBlocking")
    public edu.sdsc.nbcr.opal.types.BlockingOutputType launchJobBlocking(
        @WebParam(partName = "launchJobBlockingInput", name = "launchJobBlockingInput", targetNamespace = "http://nbcr.sdsc.edu/opal/types")
        edu.sdsc.nbcr.opal.types.JobInputType launchJobBlockingInput
    ) throws FaultType;
}
